# This is a basic workflow to help you get started with Actions

name: VsVim CI

on:
  push:
    branches: [ "master", "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master", "main", "dev/gha" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows-build:
    name: Windows Build and Test
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Build
        shell: powershell
        run: Scripts\Build.ps1 -ci -config Debug -build 

      - name: Test
        shell: powershell
        run: Scripts\Build.ps1 -ci -config Debug -test

      - name: Test Extra
        shell: powershell
        run: Scripts\Build.ps1 -ci -config Debug -testExtra

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Logs
          path: Binaries\Logs

