# This is a basic workflow to help you get started with Actions

name: VsVim CI

on:
  push:
    branches: [ "master", "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master", "main", "dev/gha" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows-publish:
    name: Publish VSIX
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Build VSIX
        shell: powershell
        run: Scripts\Build.ps1 -ci -build -updateVsixVersion -config Release
      - name: Upload VSIX Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Vsix
          path: Binaries\Deploy
